### PR TITLE
Enabling a way to create an IMP with a supplied CPL instead of calling CPLBuilder.

### PR DESCRIPTION
**Pull request by danielhdz13-netflix**

### CODE REVIEW

**Comment by danielhdz13-netflix** [comment]
Added these functions to perform testing. Once the correct functionality is verified, will need to refactor to adhere by DRY principles. Lots of duplicate code currently.

**Comment by palemieux** [comment]
What issue/problem is this solving?

**Comment by danielhdz13-netflix** [comment]
Hi @palemieux, up to this point, building a new IMP has always implied building a new CPL. On one hand, we have a case where an originally delivered CPL references tracks (A, B, C), and a new CPL references (D). In such a case, we may want to generate a new CPL that references (A, B, C, D), and that is essentially what IMPBuilder does, as long as tracks (A, B, C, D) are provided in the virtualTracks parameter. 

However, there might be a case where a redelivered CPL references files that were already delivered (e.g., [A, B, C, D] after receiving [A, B, C]). In that case, we don't need to generate a new CPL. All we need is a new PKL and AssetMap. Currently, IMPBuilder only supports generating the entire IMP, meaning we might end up with two CPLs (the originally delivered one, and the one generated by IMPBuilder) that are identical, but have different UUIDs. This has caused some pain for us, forcing us to construct a mapping between these UUIDs to arrive at the originally delivered CPL. 

This PR provides the ability to construct a new IMP without necessarily creating a new CPL. Unfortunately, to avoid altering the signature of IMPBuilder's methods, I had to add duplicate code. I will be refactoring the code where possible to minimize this, it's ongoing work. I hope this provided more context for the change!

cc @fschleich, did I miss anything?

**Comment by palemieux** [comment]
@danielhdz13-netflix Thanks for the detailed info! Funny coincidence... I just finished an initial pass at a [similar tool in Python](https://github.com/sandflow/repkl), which repackages a Composition (whose assets are possibly split across multiple deliveries) into a single Package and Delivery.

**Pull request merged**
